//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasXPagar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conceptodepago
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
    }
}
