//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasXPagar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cuentasporpagarEntities : DbContext
    {
        public cuentasporpagarEntities()
            : base("name=cuentasporpagarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<conceptodepago> conceptodepago { get; set; }
        public DbSet<entradadocumentos> entradadocumentos { get; set; }
        public DbSet<proveedores> proveedores { get; set; }
        public DbSet<transacciones> transacciones { get; set; }
    }
}
