//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasXPagar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entradadocumentos
    {
        public int NumeroDocumento { get; set; }
        public int NumeroFactura { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public double Monto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int ProveedorID { get; set; }
        public string Estado { get; set; }
    
        public virtual proveedores proveedores { get; set; }
    }
}
