//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasXPagar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transacciones
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int AuxiliarId { get; set; }
        public int Cuentas_DB { get; set; }
        public int Cuenta_CR { get; set; }
        public System.DateTime FechaTransaccion { get; set; }
        public double Monto { get; set; }
        public Nullable<int> AsientoId { get; set; }
    }
}
